version: '3.9'
services:
  postgres:
    image: 'debezium/postgres:15-alpine'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    restart: always
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    depends_on:
#      - prometheus
#    ports:
#      - "3000:3000"
